feature: add Patrolling FILTER to select command
beyond-all-reason/spring pull request #1060
Opened 2023-11-04 06:35 UTC by benmarsden

This PR adds support for filtering units based on whether they are patrolling or not when using select commands.

The benefit of this change is that it becomes possible to exclude units with long-running patrol tasks (e.g., defending expansions without LLTs) from select commands. For example, `AllMap+_Not_Builder_Not_Building_Not_Patrolling+_ClearSelection_SelectAll+`.

For some small addition context/discussion, see [this](https://discord.com/channels/549281623154229250/1018861299939168288/1169735003630997524) Discord thread.

2023-11-04 15:05 UTC, badosu approved these changes

2023-11-04 15:09 UTC, sprunk commented
tested ingame?

2023-11-04 15:59 UTC, benmarsden commented
> tested ingame?

No, and I won't have time to set up compilation locally in the short-term (first-time contributor). Is this a blocker in your opinion? Would it be an option to test this using one of the pre-release binaries (which I can do), or for another contributor to test it?

2023-11-04 16:04 UTC, sprunk commented
> Is this a blocker in your opinion?

yes because i don't believe this actually works

2023-11-05 09:35 UTC, badosu requested changes
Blocked by in-game test

2023-11-05 10:20 UTC, badosu commented
Testing it, patrol seems tricky (it creates two fight commands)

2023-11-05 14:41 UTC, badosu commented
Superseded by #1061

2023-11-05 14:41 UTC, closed without merging