Fix SetUnitPosition documentation
beyond-all-reason/spring pull request #1363
Opened 2024-03-14 08:15 UTC by Arch-Shaman

Documentation claims only 3 params (x, z, alwaysAboveSea) but there's a hidden optional y param.

2024-03-14 08:42 UTC, lhog commented
I'm not sure if this fix is correct.
The documentation relies on the position of arguments, "optional" doesn't mean it's skipped.

It should be something like:

```
 * @number unitID
 * @number x
 * @number y | number z
 * @number z | bool[opt] alwaysAboveSea
 ```
 At least conceptually, the syntax above might be completely off.

2024-03-14 11:59 UTC, sprunk commented
AFAIK there is some way to specify two separate sets of args like
```
@function Spring.SetUnitPosition
@number x
@number z
@bool[opt] alwaysAboveSea

@some_tag_to_make_it_reset_and_start_an_alternate_set_of_args
@function Spring.SetUnitPosition
@number x
@number y
@number z
```
but also maybe that's just a bad interface for a function to have two different sets of args. Perhaps the x/z/bool version should just become `SetPositionXZ` or something?

2024-03-18 02:22 UTC, badosu requested changes
Thanks for the contribution, consider something like this:

```cpp
/*** Set unit position (2D)
 * @function Spring.SetUnitPosition
 * @number unitID
 * @number x
 * @number z
 * @bool[opt=false] alwaysAboveSea whether cap minimum height by sea level
 * @treturn nil
 */


/*** Set unit position (3D)
 * @function Spring.SetUnitPosition
 * @number unitID
 * @number x
 * @number y
 * @number z
 * @treturn nil
 */
```

It's possible to use optional types for the multiple args possibilities, but that makes the documentation too confusing.

2024-03-18 02:39 UTC, badosu commented
> AFAIK there is some way to specify two separate sets of args like
> 
> ```
> @function Spring.SetUnitPosition
> @number x
> @number z
> @bool[opt] alwaysAboveSea
> 
> @some_tag_to_make_it_reset_and_start_an_alternate_set_of_args
> @function Spring.SetUnitPosition
> @number x
> @number y
> @number z
> ```
> 
> but also maybe that's just a bad interface for a function to have two different sets of args. Perhaps the x/z/bool version should just become `SetPositionXZ` or something?

Definitely an antipattern that's present in a lot of places.

2024-03-18 14:48 UTC, badosu approved these changes
LGTM, move long description in a new line below `@function`

2024-03-18 16:15 UTC, merged

2024-03-18 17:21 UTC, badosu commented
@Arch-Shaman Thank you for the contribution, the website should be updated in a day or so