check aim from the weapon's position and direction
beyond-all-reason/spring pull request #1454
Opened 2024-04-18 15:34 UTC by marcushutchings

Units with rotation turrets and an aim constraint can find themselves unable to fire unless the front of the unit has rotated enough towards the weapon's target so that the starting direction of the weapon + the unit's front is within the tolerance. The issue can manifest with say armraz, where the guns are unable to fire (if a constraint is enforced see https://github.com/beyond-all-reason/spring/pull/1452) until the unit turns the legs around to face the target.

2024-04-18 22:42 UTC, sprunk requested changes
That behaviour is the whole point of the tag.

2024-04-18 22:44 UTC, sprunk commented
Also it fails for weapons with trajectoryHeight.

2024-04-19 06:35 UTC, marcushutchings commented
> That behaviour is the whole point of the tag.

I don't understand what you are referring to. Please elaborate. I don't understand what tag was ever supposed to stop a constrained weapon from firing at something it is pointing directly at because the unit's legs were facing the other way.

2024-04-19 06:42 UTC, marcushutchings commented
> Also it fails for weapons with trajectoryHeight.

A 2D arc check would solve that. Though, will there be any issues with units being able to shoot near 90 degrees up down? If not then the adjustment is simple. If there isn't then I'll need to add some extra checks.

2024-04-19 11:05 UTC, sprunk commented
> I don't understand what tag was ever supposed to stop a constrained weapon from firing at something within its permitted firing arc because the unit's legs were facing the other way (when the weapon wasn't explicitly tagged as front facing only.)

`maxAngleDif` controls the arc in relation to `mainDir`.
`mainDir` (and thus the arc) is relative to the unit (i.e. "legs"), and within unit space it is static (so the only way to point it in a different world-space direction is to rotate the whole unit, i.e. "make legs face the correct way").

> `CheckTargetAngleConstraint()` does the front-facing restriction check if needed. That isn't affected.

I tested and it was affected. I didn't test current head so hopefully it's this patch and not something already merged recently. I'm not at home at the moment, i'll send some screenshots in about 10 hours.

2024-04-19 11:10 UTC, sprunk commented
The use case for firing arcs is "battleship" style turrets. They are not meant to aim backwards, the whole body of the unit is supposed to rotate to put targets in the turret's firing arc.
![image](https://github.com/beyond-all-reason/spring/assets/2573076/c7d4932c-df55-4a7d-a036-2a4a631ac8ff)

2024-04-19 11:12 UTC, marcushutchings commented
What you are explaining there means there is no way to have a turret with a 90 degree firing arc ever fire behind the unit.

2024-04-19 11:14 UTC, sprunk commented
Set `mainDir = [[0 0 -1]]`?

2024-04-19 11:15 UTC, marcushutchings commented
> > I don't understand what tag was ever supposed to stop a constrained weapon from firing at something within its permitted firing arc because the unit's legs were facing the other way (when the weapon wasn't explicitly tagged as front facing only.)
> 
> `maxAngleDif` controls the arc in relation to `mainDir`. `mainDir` (and thus the arc) is relative to the unit (i.e. "legs"), and within unit space it is static (so the only way to point it in a different world-space direction is to rotate the whole unit, i.e. "make legs face the correct way").
> 
> > `CheckTargetAngleConstraint()` does the front-facing restriction check if needed. That isn't affected.
> 
> I tested and it was affected. I didn't test current head so hopefully it's this patch and not something already merged recently. I'm not at home at the moment, i'll send some screenshots in about 10 hours. Generally get a ZK `gunshipkrow` and target ground randomly around the unit until you get all 3 guns firing at the same spot. This shouldn't be possible because the arcs are set up such that at most 2 overlap.

Did you test weapon with `onlyForward` flag set?

2024-04-19 11:18 UTC, sprunk commented
Not yet, I'll be back home in 10h and test more.

2024-04-19 11:23 UTC, marcushutchings commented
> Set `mainDir = [[0 0 -1]]`?

We're talking about different things here. Okay. You're talking about a fix placement turret. Okay. I see where my change would impact the original intent.

However, we have another issue, which looks to be a new case. A Razorback can rotate its body, separate to the legs. From what we already have the turret technically can fire in any direction --- however, this is a problem, because the unit can shoot out the back of the gun to hit an enemy behind it. We can't use the current restrictions because the turret could go outside the aim angle and then wouldn't be able to fire (which looks bad), but it would still be able to shoot through itself if the legs are facing the target.

Okay. I'll fix this up. Thanks for your patience.

2024-04-19 11:42 UTC, sprunk commented
> You're talking about a fix placement turret. Okay. I see where my change would impact the original intent.

Yes, though I think `onlyForward` is supposed to behave the same as `mainDir = [[0 0 1]]` as far as aiming/targeting is concerned. I am not sure what the full list of differences is, there's a ticket to discover it #1449

> the turret technically can fire in any direction --- however, this is a problem, because the unit can shoot out the back of the gun to hit an enemy behind it.

There's `maxFireAngle` which I believe is meant to do what you want. AFAIK right now it only works for the first shot in a burst though. https://github.com/beyond-all-reason/spring/blob/6cefa051663284da0043c12075f11da45808dfda/rts/Sim/Weapons/WeaponDef.h#L96

I think it would be fine to extend it. A minor issue to keep in mind when checking it out: #1450

2024-04-19 13:05 UTC, marcushutchings commented
maxFir

> Somewhat relatedly: it would be good if there was a debug mode that showed weapon vectors, each in unique color:
> 
>     * direction of the piece returned from QueryPiece
> 
>     * direction of the piece returned from AimFromPiece
> 
>     * direction of the `weaponDir` because it seems used a lot but not identical with any of the others
> 
>     * cone of firing arc
> 
> 
> AFAIK the former two may be shown in `/debugcolvol` already but they are directionless balls showing just the piece origin and not rotation.

Sounds like a good ticket,

2024-04-19 13:08 UTC, marcushutchings commented
> > You're talking about a fix placement turret. Okay. I see where my change would impact the original intent.
> 
> Yes, though I think `onlyForward` is supposed to behave the same as `mainDir = [[0 0 1]]` as far as aiming/targeting is concerned. I am not sure what the full list of differences is, there's a ticket to discover it #1449
> 
> > the turret technically can fire in any direction --- however, this is a problem, because the unit can shoot out the back of the gun to hit an enemy behind it.
> 
> There's `maxFireAngle` which I believe is meant to do what you want (ZK seems to set it to 360° for most units so I'm not that familiar with it). AFAIK right now it only works for initiating the burst though.
> 
> https://github.com/beyond-all-reason/spring/blob/6cefa051663284da0043c12075f11da45808dfda/rts/Sim/Weapons/WeaponDef.h#L96
> 
> I think it would be fine to extend it to also work on the bursts. A minor issue to keep in mind when checking it out: #1450

Thanks. I'm trying it out, but it doens't seem to be working. Though I can't quite get my head around how these angles work for this purpose. It doesn't look like it matches the weapon model angles. I'll play around with it some more.

2024-04-19 14:17 UTC, sprunk commented
Razorback has a burst so the current implementation of `firetolerance` won't work for it.

2024-04-19 14:23 UTC, marcushutchings commented
The question is, how do we achieve this for burst? Direct line, aiming is easy enough, but for weapons that want to aim upwards, that's more involved. We may have to force an AimWeapon script call when the target changes?

2024-04-19 14:30 UTC, sprunk commented
> The question is, how do we achieve this for burst?

I don't know, I'm just saying that I believe `firetolerance` is the correct tag to use here and that it works for non-burst (burst=1) weapons.

> Direct line, aiming is easy enough, but for weapons that want to aim upwards, that's more involved.

I don't think this matters. Ballistic weapons still fundamentally aim in a direct line at some direction in the sky, just the direction is carefully picked so that the projectile manages to fall down onto the target.

> We may have to force an AimWeapon script call when the target changes?

This would be good but doesn't solve all cases. The target can be a unit which can then just move to the other side of the shooter. The best example is a teleport ability but even without Lua you can have very fast aircraft fly overhead.

2024-04-19 14:40 UTC, marcushutchings commented
I see. yes, I think `firetolerance` sounds like the right parameter.

2024-04-19 16:28 UTC, marcushutchings commented
Closing. This isn't the way forward.

2024-04-19 16:28 UTC, closed without merging