Save and restore extraction map.
beyond-all-reason/spring pull request #1744
Opened 2024-10-31 15:21 UTC by saurtron

### Work done

* Added serialization for MetalMap.extractionMap inside ReadMap.

### Considerations

* Not sure if this is the best way to save the data.
* This will break compatibility with older saves, any way to avoid that?
* I thought to do PostLoad on Extractors instead, thus re-initializing the extraction map without saving additional data, but dont' think that works because several extractors can be in the same spot, thus loading them in different order could result in different initialization. If unit load ordering is guaranteed to be the same of unit creation order, then I think that can work, but might be more fragile not sure. This method should be robust.

### Related issues

See https://github.com/beyond-all-reason/Beyond-All-Reason/issues/1489

Extraction map didn't get saved, thus metal visualization is wrong and also on load game this will cause accounting errors for the metal extractors (experienced as extractors with multiples of expected income production). Above issue has several screenshots.

### Why

Initially the extraction map is set to all 0s.

When a metal extractor is built, updates the map to it's extraction value. This way when another extractor can come later they can share the metal if the latter one is t2. Later one will overwrite values, but deduct the original value from its available income.

Not loading the extractionMap means it will be initialized to 0, but metal extractors will be present in the map, so when one of them is destroyed, it will call [CMetalMap::RemoveExtraction](https://github.com/beyond-all-reason/spring/blob/1cc2b11f7c777bbe6634b3a53eb2241baabab5f0/rts/Map/MetalMap.cpp#L123) deducting its value to below 0. That way when another extractor comes afterwards in the same place, it will request X extraction, but [obtain more](https://github.com/beyond-all-reason/spring/blob/1cc2b11f7c777bbe6634b3a53eb2241baabab5f0/rts/Map/MetalMap.cpp#L109).

Note metal extractors seem to be saving and loading all of the relevant data they need, so the extractionMap seems to be the only missing part to keep accounting and spot visualization right.

2024-10-31 15:57 UTC, sprunk commented
> This will break compatibility with older saves, any way to avoid that?

IMO not a worry, saves are supposed to contain engine version info and can still be run on their appropriate engine version.

> If unit load ordering is guaranteed to be the same of unit creation order, then I think PostLoad can work

Apparently the `activeUnits` vector is kept in creation order:
https://github.com/beyond-all-reason/spring/blob/1cc2b11f7c777bbe6634b3a53eb2241baabab5f0/rts/Sim/Units/UnitHandler.cpp#L215-L217
https://github.com/beyond-all-reason/spring/blob/1cc2b11f7c777bbe6634b3a53eb2241baabab5f0/rts/Sim/Units/UnitHandler.cpp#L316

Perhaps check whether it can be (or if it is) used in saving units.

2024-10-31 17:58 UTC, saurtron commented
> Perhaps check whether it can be (or if it is) used in saving units.

I checked and the PostLoad order is not the same as activeUnits order, also, activeUnits is updated as soon as the blueprint is placed so also not the order needed here, besides, when disabling and enabling a unit the activeUnits order also stays (also important here). PostLoad order also is not unit creation order, it's quite random.

Anyways, current solution in ReadMap is quite clean since it doesn't pollute other files.

I think doing it in PostLoad would require more ad-hoc code and probably be more fragile.

Maybe it could be cleaner by hooking the metalMap directly to [CregLoadSaveHandler](https://github.com/beyond-all-reason/spring/blob/1cc2b11f7c777bbe6634b3a53eb2241baabab5f0/rts/System/LoadSave/CregLoadSaveHandler.cpp#L84) so it wouldn't need "so much code" to serialize, but I think it would also want to serialize other members we don't need. To serialize just that buffer it doesn't get much more compact, could be made into one liner, and even put in the CregLoadSaveHandler directly, but would be the same thing basically just in a different file.

Anyways, maybe someone who knows the serializer and object system knows a better way of course. Happy to change it how you like it more.

2024-10-31 22:18 UTC, sprunk commented
> could be cleaner by hooking the metalMap directly to CregLoadSaveHandler but I think it would also want to serialize other members we don't need

You can mark members as ignored. In fact it seems to already be marked:
https://github.com/beyond-all-reason/spring/blob/1cc2b11f7c777bbe6634b3a53eb2241baabab5f0/rts/Map/MetalMap.cpp#L14-L22

I am unsure how the other non-ignored member, distributionMap, works with save/load at the moment. Perhaps it actually doesn't and just uses whatever the map starts with, and only appears to work because games barely ever modify it at runtime.

I think the code is alright as-is though, figuring out what happens if you modify the distribution map at runtime and/or simplifying it via creg aren't vital and could be done as a follow-up anytime.

2024-10-31 22:18 UTC, sprunk approved these changes
It may be a matter of marking

2024-11-01 00:58 UTC, saurtron commented
Well, I prepared another alternative PR #1745 saving the object directly. Seems it's the better approach and simpler code too, that way it also saves the distributionMap.

I wasn't sure about setting other members to ignored but I follow your guidance in saying that CR_IGNORED will just make the serializer ignore them.

I overlooked the distributionMap initially, just thought nothing else needed to be saved, but yeah there's an api to modify it during the game.

2024-11-01 01:43 UTC, sprunk requested changes
IMO #1745 is the superior implementation.

2024-11-01 08:36 UTC, closed without merging

2024-11-01 08:36 UTC, saurtron commented
ok, closing this one in favour of #1745